@url = https://1b23dsztp3.execute-api.us-east-1.amazonaws.com/sentiment-analysis     

###
POST {{url}}
Content-Type: application/json

{
   "text": "The weather is sunny and I plan to play basketball with my kids" 
}
